version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - shop
    volumes:
      - mysql-data:/var/lib/mysql

  helmet-shop:
    image: waang07/helmet-shop:latest
    restart: always
    networks:
      - shop
    env_file:
      - ./.env

volumes:
  mysql-data:

networks:
  shop:
    driver: bridge
